# Generated by Django 5.0.3 on 2024-04-26 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lname',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
